---
title: "Covstretch Function Summary"
author: "Leonardo Wang"
output: pdf_document
header-includes: 
  - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This note will summarize main functions for simulation and optimization from the **covstretch** repository that can potentially be utilized by the new theoretical paper on optimal doze stretching. 

# Epidemiological Model

We begin with the fundamental epidemiological model. The associated system of differential equations is defined originally in **R/ode_2vaccines_v2.R**, now moved to **review/setup/epi_models.R**, and can be formally written as below. The model contains two vaccine types with different efficacies. Since we are only considering the case of fractional dose, we ignore the second vaccine type in reality. 

\begin{align}
\dot{S}_i(t) &= - \lambda_i(t) S_i(t) + \phi_i R_i(t) - (v_i^1(t) \delta_t^1 - v_i^2(t) \delta_t^2) \frac{S_i(t)}{S_i(t) + R_i(t)} \\
\dot{E}_i(t) &= \lambda_i(t) (S_i(t) + N_i^1(t) + N_i^2(t)) - \gamma_i^{EI} E_i(t) \\
\dot{I}_i(t) &= \gamma_i^{EI} E_i(t) - \gamma_i^{IRD} I_i(t) \\
\dot{R}_i(t) &= (1 - p_i) \gamma_i^{IRD} I_i(t) - \phi_i R_i(t) - (v_i^1 \delta_i^1 + v_i^2 \delta_i^2) \frac{R_i(t)}{S_i(t) + R_i(t)} \\
\dot{D}_i(t) &= p_i \gamma_i^{IRD} I_i(t) \\
\dot{V}_i^1(t) &= v_i^1(t) \delta_i^1 \frac{e_i^1 S_i(t) + R_i(t)}{S_i(t) + R_i(t)} - \kappa_i^1 V_i^1(t) \\
\dot{N}_i^1(t) &= v_i^1(t) \delta_i^1 \frac{(1 - e_i^1) S_i(t)}{S_i(t) +  R_i(t)} + \kappa_i^1 V_i^1(t) - \lambda_i(t) N_i^1(t) \\
\dot{V}_i^2(t) &= v_i^2(t) \delta_i^2 \frac{e_i^2 S_i(t) + R_i(t)}{S_i(t) + R_i(t)} - \kappa_i^2 V_i^2(t) \\
\dot{N}_i^2(t) &= v_i^2(t) \delta_i^2 \frac{(1 - e_i^2) S_i(t)}{S_i(t) + R_i(t)} + \kappa_i^2 V_i^2(t) - \lambda_i(t) N_i^2(t) 
\end{align}

where the definitions can be found in the appendix to the PNAS paper. Note that $\phi_i$ denotes loss of immunity. 

# Parameters

Parameters are defined in **review/parameters_scenario.R** and can be conveniently accessed by the function **grab_2v_parms**. The function **apap_2v** for age prioritization adjustment is stored in **review/parameters_adj_age_prioritization.R**. 

* $\lambda_i(t) = q \sum_{j=1}^G c(i,j) I_j(t)$: rate of new infection, $c(i,j)$ denotes the number of contacts made by an individual in cohort $i$ with another in cohort $j$, $q$ is adjusted match the reproductive number of virus $\mathcal{R}$.
The contact matrix $C$ is contained in **review/setup/default_input.Rdata**. $q$ is 

* $\gamma_i^{EI}$: hazard rate of moving from exposed to infected, set to 0.2. 
* $\gamma_i^{IRD}$: hazard rate of moving from infected to recovered or dead, set to 0.2.
* $p_i$: mortality risk
* $e_i^1$: efficacy of fractional dose. It is by default 0.95. Later in **objective-function.R**, it will be according to a response function of dose fraction. 
* $e_i^2$: efficacy of the second vaccine, set to 0. 
* $v_i$: eligibility of vaccination
* $\delta_i$: rate of vaccination
* $\phi_i$: loss of immunity, currently 0 for all groups

# Initial Values

# Dynamic Optimization

## Single Simulation

The **single_run** function, stored in **review/simulation/single_run.R**, will run the epidemiological model for 360 days. As the real work horse, it takes in parameters and initial values, and outputs the matrix $y$, rows of which are days and columns of which are compartments in the model. 

## Objective Function

Note the **main_matrics** function





















